### ISSUE TITLE
Changement du nom de domaine de torrent9

### ISSUE THREAD

**Issue by Olosikana** [piwi82/Synology#2]
Bonjour,
Merci pour votre travail, cette fonction est bien pratique, mais suite au changement de domaine du tracker, le plugin v0.2 ne fonctionne plus. J'ai essayé de modifier le ficher php en remplaçant la variable HOST par www.torrent9.bz. La recherche fonctionne et renvoie des résultats cohérents mais download station télécharge la page web du torrent au lieu du fichier .torrent. J'imagine qu'il y a dû y avoir des changements dans la structure du site... N'ayant aucune base en php, je suis assez démuni pour résoudre ce problème. Pensez-vous qu'une mise à jour serait faisable ?
Merci.

**Comment by piwi82** [comment]
Oui c'est faisable, je regarde dès que j'ai un peu de temps.
Merci pour le signalement 😉

**Comment by piwi82** [comment]
Salut @Olosikana , j'ai pu mettre à jour le module et il y avait effectivement des changements du côté de Torrent9.
- Le nom de domaine est maintenant `torrent9.red`,
- L'URL des pages d'un lien torrent contient maintenant un identifiant qui n'existait pas auparavant. L'expression régulière correspondante servant à générer les liens de téléchargement a été mise à jour.

Je clôturerai ce message lorsque toi ou quelqu'un d'autre aura validé le bon fonctionnement du module.

**Comment by Olosikana** [comment]
Bonjour @piwi82 , merci pour cet update, je te confirme que tout fonctionne correctement !
C'est parfait :+1:
